### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#64]

**Comment by axelgarciahenriksson** [comment]
Is this how to handle dark modes in Operating systems, eg iOS / Mac OS? Or a new optional dark mode of our own in web channels? Private Banking sometimes talk about dark mode as a sober more premium feel. Dark blue backgrounds et al. Internally, that is. The clients haven’t expressed any thoughts about this.

**Comment by hjalmers** [comment]
The new iOS version iOS 13 introduces dark mode so a very likely scenario is that our native apps will get a dark mode too (like some of our competitors), if we include web views (web apps) in our native apps they need to support dark mode too unless we want them to stay "white". Adding a dark mode without agreeing on a common format for markup will most likely get pretty messy and ugly I'm afraid since we haven't agreed on one but multiple frameworks and markup conventions:(...

**Comment by eskolehtme** [comment]
Here is a quick introduction to the dark mode. The noteworthy parts are about the new naming conventions for typographical styles (primary, secondary …) and how Apple pays close attention to the color contrasts in light and dark modes.

https://developer.apple.com/videos/play/wwdc2019/808/

**Comment by hjalmers** [comment]
@eskolehtme yeah I like the way apple thinks about colors and it's pretty easy to implement in our native apps but when it comes to our web interfaces it's a different matter I'm afraid. Our bootstrap theme uses pretty much the same convention as apple as it's built around semantic names for colors, each semantic color has class names for different contexts as well such as `text-*` (for texts), `bg-*` (for backgrounds), `alert-*` (for alerts/notifications) etc.  just to give a brief example of how this can be used in practice:

### Normal mode

```html
<html>
  <body class="bg-light">
    <p class="text-danger">Red warning text light background</p>
    <button class="btn btn-danger">Red delete button</button>
  </body>
</html>
```

### Dark mode
Add the class `dark-mode` to html or body element. 
```html
<html class="dark-mode">
  <body class="bg-light">
    <p class="text-danger">Red warning text light background</p>
    <button class="btn btn-danger">Red delete button</button>
  </body>
</html>
```
This is an example of a sass file for generating the needed css.
```scss
.bg-light {
  background: $light-gray;
}
.text-danger {
  color: $danger-darker;
}
.btn-danger {
  background: $danger-darker;
}
/* adjust the values when dark-mode is applied to a parent element */
.dark-mode {
  .bg-light {
    background: $dark-gray;
  }
  .text-danger {
    color: $danger-lighter;
  }
  .btn-danger {
    background: $danger-lighter;
  }
}
```

However in order for this to work we need to enforce the naming and use of classes. Usually when we create prototypes we specify a colors like background should be `#f8f8f8`, text should be `#343434` instead of using `$bg-light` and `$text-dark` which could have different values depending normal or dark mode or even a high contrast mode for people with color blindness for example. I think it would be great if we could avoid using hex values and start thinking about the semantic meaning of colors as most teams tend to just "hard code" the hex value, even using dynamic names like `seb-green` should be avoided in my opinion as it might be a different color in another mode, especially if you're color blind.
